version: '1.0'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo_final
    ports:
      - "27017:27017"
    volumes:
      - D:\OneDrive - Vanderbilt\Desktop\Hillbert's PC Files\My Grad Life\Fall 2024\DS5760_NoSQL\FinalProject\ds5760_project:/ds5760/final_project
    # environment: # disabling this for class practice only
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: examplepassword

  neo4j:
    image: neo4j:latest
    ports: 
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    environment:
      NEO4J_AUTH: 'neo4j/password' # username/password
    volumes:
      - D:\OneDrive - Vanderbilt\Desktop\Hillbert's PC Files\My Grad Life\Fall 2024\DS5760_NoSQL\FinalProject\ds5760_project:/ds5760/final_project
